name: Update Changelog

on:
  push:
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Changelog using git log
        run: |
          git log --pretty=format:"%d%n%n%h - %an, %ad : %s" --date=iso --decorate > CHANGELOG.md

      - name: Commit and push changelog
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add CHANGELOG.md
          git commit -m "chore(release): update CHANGELOG.md"
          git push origin main
